exclude: _pb2\.py$
repos:
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
- repo: https://github.com/asottile/yesqa
  rev: v1.2.2
  hooks:
  - id: yesqa
    additional_dependencies:
    - flake8-bugbear==20.1.4
    - flake8-builtins==1.5.2
    - flake8-comprehensions==3.2.2
    - flake8-tidy-imports==4.1.0
    - flake8==3.7.9
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    - id: check-docstring-first
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: requirements-txt-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: a4aeb2e209c64efcfadb43cb96809c1f5b80912b
    hooks:
    -   id: flake8
- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.3
  hooks:
  - id: pyupgrade
    args: ['--py36-plus']
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.7.0
  hooks:
  - id: python-check-mock-methods
  - id: python-use-type-annotations
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 9feadeb
  hooks:
  - id: mypy
    args: [--ignore-missing-imports, --warn-no-return, --warn-redundant-casts, --disallow-incomplete-defs]
